### ISSUE TITLE
No available background worker slots

### ISSUE THREAD

**Issue by karpinovsky** [timescale/timescaledb#1061]
**Relevant system information:**
 - Ubuntu 16.04
 - psql (PostgreSQL) 9.6.11
 - timescaledb-0.10.1
 - using Docker

**Describe the bug**
Hello, I stuck with docker-compose up
```
c@ubuntu-s-2vcpu-4gb-fra1-01:~/klines$ docker-compose up
Creating network "klines_default" with the default driver
Creating klines_db_1 ... done
Creating klines_app_1 ... done
Attaching to klines_db_1, klines_app_1
db_1   | LOG:  database system was shut down at 2019-02-13 05:43:43 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started
db_1   | LOG:  TimescaleDB background worker launcher connected to shared catalogs
db_1   | LOG:  no available background worker slots
db_1   | HINT:  Consider increasing max_worker_processes in tandem with timescaledb.max_background_workers.
db_1   | LOG:  TimescaleDB version $libdir/timescaledb-0.10.1 does not have a background worker, exiting
db_1   | LOG:  TimescaleDB version $libdir/timescaledb-0.10.1 does not have a background worker, exiting
```

docker-compose.yml
```
version: "3"
volumes:
  db_data:
services:
  db:
    image: timescale/timescaledb
    env_file: .env
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
  app:
    build: .
    env_file: .env
    restart: always
    ports:
      - "5000:5000"
      - "443:443"
    volumes:
      - "./:/app"
    command: >
      ./app/out/klines_app_linux -mode=$MODE
      -settings-file=/app/config/settings.yml
      -db-settings-file=/app/config/database.yml
      -tls-crt-file=/app/certs/fullchain1.pem -tls-key-file=/app/certs/privkey1.pem
    depends_on:
      - db
```

What am I doing wrong?
