### ISSUE TITLE
docker-compose pull access denied for timescaledb

### ISSUE THREAD

**Issue by ikks** [timescale/timescaledb#1259]
With the following bit of configuration for `docker-compose.yml`
```
  timescaledb:
    image: timescale/timescaledb-postgis:latest-pg11
    ports:
      - "15432:5432"
    build:
      context: .
```
When Running
```
docker-compose up
```
I'm gettting
```
ERROR: Service 'timescaledb' failed to build: pull access denied for timescaledb/timescaledb-postgis:latest-pg11, repository does not exist or may require 'docker login'
```
But if I run
```
docker pull timescale/timescaledb-postgis:latest-pg11
```
It works properly
The same happens if I try with the images `timescale/timescaledb` or `timescale/timescaledb-postgis`

Previously I was able to run `docker-compose up` without problem.

My docker-compose version is 
```
docker-compose version 1.24.0, build 0aa59064
```

Running on Linux Debian 9.9
