### ISSUE TITLE
[Bug]: add_data_node ignores if_not_exists parameter

### ISSUE THREAD

**Issue by lucebac** [timescale/timescaledb#4154]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Data node

### What happened?

When I tried to add an existing data node to a fresh access node, the `add_data_node('ts-data1', host => 'ts-data1', if_not_exists => TRUE)` call fails with an error stating that `DETAIL:  ERROR:  node is already a data node`. However, [according to the documentation](https://docs.timescale.com/api/latest/distributed-hypertables/add_data_node/) passing the `if_not_exists` optional parameter should avoid raising a fatal error and only log a notice message instead. Apparently, this does not work as expected in my setup and thus I end up with a fatal error and my access node not booting up.

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14

### What operating system did you use?

Docker on Ubuntu 20.04 x64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/10-setup.sql
psql:/docker-entrypoint-initdb.d/10-setup.sql:2: NOTICE:  database "mydb" already exists on data node, skipping
psql:/docker-entrypoint-initdb.d/10-setup.sql:2: NOTICE:  extension "timescaledb" already exists on data node, skipping
DETAIL:  TimescaleDB extension version on ts-data1:5432 was 2.6.0.
2022-03-08 18:18:17.743 UTC [81] ERROR:  cannot add "ts-data1" as a data node
2022-03-08 18:18:17.743 UTC [81] DETAIL:  ERROR:  node is already a data node

2022-03-08 18:18:17.743 UTC [81] STATEMENT:  SELECT * FROM add_data_node('ts-data1', host => 'ts-data1', if_not_exists => TRUE);
psql:/docker-entrypoint-initdb.d/10-setup.sql:2: ERROR:  cannot add "ts-data1" as a data node
DETAIL:  ERROR:  node is already a data node
```

### How can we reproduce the bug?
Steps to repoduce (you might need to `chmod 644 access.sql`; however, this is unrelated to the reported issue):
1) Boot data node: `docker-compose up -d ts-data1`
2) Boot access node: `docker-compose run --rm ts-access` -- everything is fine, you can insert and query data from the distributed hypertable as expected
3) Stop and remove access node: Ctrl+C 
4) Boot up a fresh access node again: `docker-compose run --rm ts-access` -- the error should occur as soon as the init scripts are run

`docker-compose.yml`
```yml
version: '3'

x-envs: &envs
  POSTGRES_DB: "mydb"
  POSTGRES_PASSWORD: "insecure"

# command line changes come from the timescale docs:
# https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-config/#update-settings

services:
  ts-access:
    image: timescale/timescaledb:latest-pg14@sha256:4c2133de750eb69f35d8a0875a68903e6c8f43622473a99f1de5ccddd9b9dd80
    command:
      - "-cmax_prepared_transactions=150"
      - "-cenable_partitionwise_aggregate=yes"
      - "-cjit=off"  # must be set to off on the access node
    environment:
      <<: *envs
    depends_on:
      - ts-data1
    volumes:
      - ./access.sql:/docker-entrypoint-initdb.d/10-setup.sql:ro

  ts-data1:
    image: timescale/timescaledb:latest-pg14@sha256:4c2133de750eb69f35d8a0875a68903e6c8f43622473a99f1de5ccddd9b9dd80
    command:
      - "-cmax_prepared_transactions=150"
      - "-cjit=on"
      - "-cstatement_timeout=0"  # must be 0 on data nodes
    environment:
      <<: *envs
      POSTGRES_HOST_AUTH_METHOD: "trust" # effectively allows connection from anywhere to any database -- don't use this in prod
```

`access.sql`
```sql
SELECT * FROM add_data_node('ts-data1', host => 'ts-data1', if_not_exists => TRUE);

CREATE TABLE IF NOT EXISTS mytable (
    ts_col TIMESTAMP
);

SELECT create_distributed_hypertable(
    'mytable', 'ts_col'
);
```

**Comment by lucebac** [comment]
Since the formatting in the original post was a bit off, I edited it and append the files again here:
`docker-compose.yml`
```
version: '3'

x-envs: &envs
  POSTGRES_DB: "mydb"
  POSTGRES_PASSWORD: "insecure"

# command line changes come from the timescale docs:
# https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-config/#update-settings

services:
  ts-access:
    image: timescale/timescaledb:latest-pg14@sha256:4c2133de750eb69f35d8a0875a68903e6c8f43622473a99f1de5ccddd9b9dd80
    command:
      - "-cmax_prepared_transactions=150"
      - "-cenable_partitionwise_aggregate=yes"
      - "-cjit=off"  # must be set to off on the access node
    environment:
      <<: *envs
    depends_on:
      - ts-data1
    volumes:
      - ./access.sql:/docker-entrypoint-initdb.d/10-setup.sql:ro

  ts-data1:
    image: timescale/timescaledb:latest-pg14@sha256:4c2133de750eb69f35d8a0875a68903e6c8f43622473a99f1de5ccddd9b9dd80
    command:
      - "-cmax_prepared_transactions=150"
      - "-cjit=on"
      - "-cstatement_timeout=0"  # must be 0 on data nodes
    environment:
      <<: *envs
      POSTGRES_HOST_AUTH_METHOD: "trust" # effectively allows connection from anywhere to any database -- don't use this in prod
```


`access.sql`
```sql
SELECT * FROM add_data_node('ts-data1', host => 'ts-data1', if_not_exists => TRUE);

CREATE TABLE IF NOT EXISTS mytable (
    ts_col TIMESTAMP
);

SELECT create_distributed_hypertable(
    'mytable', 'ts_col'
);
