### ISSUE TITLE
Extremely slow performance - docker issue?

### ISSUE THREAD

**Issue by dss010101** [timescale/timescaledb#5665]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Distributed hypertable

### What happened?

My client app runs in a docker container.  TimescaleDB runs in separate docker.  Both under docker desktop - debian linux.
I have a pandas dataframe containing 30k records.
It takes 4.5 minutes to write this to my database table. 
Additionally if i try to query for the table that also takes over about 3 minutes.  
Even truncating the data using pgAdmin took 7 and half minutes.  
I dont think 30k reocrds should cause this kind of slow performance,   so something seem really off here.

The docker compose looks like this (the docker file is :
```
version: '3.8'

services:
  web_app:
    container_name: web_app
    image: web_app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ../database/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5050:5000
      - 5432:5432
```

I have the following table i created which im trying to upload around 30k records to:
```
DROP TABLE IF EXISTS equity_daily;
CREATE TABLE equity_daily(
    date date,
    symbol varchar(32),
    open numeric,
    high numeric,
    low numeric,
    close numeric,
    volume numeric,
    last_mod_time timestamptz default current_timestamp,
   PRIMARY KEY(symbol, date)
);
SELECT create_hypertable('equity_daily', 'date');
```
The docker file referenced in the above docker-compose is based off of: mcr.microsoft.com/devcontainers/python:0-3.11-bullseye

The client code snippet is the following:

```
        df['last_mod_time'] = 'now()'
        io_buf = io.StringIO()
        df.to_csv(io_buf, sep='\t', header=False)
        io_buf.seek(0)        
        
        conn = psycopg2.connect(self.connect_str)
        conn.autocommit = True
        with conn.cursor() as cur:
            cur = conn.cursor()
            cur.copy_from(io_buf, table='equity_daily', sep='\t')
            conn.commit()
```

Im running locally.  the system im running on is Windows 11, 16gb of RAM, 8 cores.  Not the best i know - but still doesnt seem like it should perform this poorly.  
Any help in diagnosing and resolving this would be appreciated.

### TimescaleDB version affected

"PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit"

### PostgreSQL version used

15.2

### What operating system did you use?

Windows 11 - but client in Bullseye Container, DB also in a container.

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
SELECT version();

"PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit"
```

### How can we reproduce the bug?

```bash
use above docker-compose
```
