### ISSUE TITLE
Data is deleted after upgrade 2.7 to 2.10 in docker container.

### ISSUE THREAD

**Issue by ManivannanMurugavel** [timescale/timescaledb#5964]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Other

### What happened?

I have timescaledb with 2.7 and it's running in docker container. But I need to run the time_bucket for "1 month", "1 year" and etc. My version is not compatiable to run, So that I upgraded to 2.10 based on this link "https://docs.timescale.com/self-hosted/latest/upgrades/upgrade-docker/". After updation, my data is not exists. 

docker-compose.yml:
```
ersion: '3.7'
services:
#
  service:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: "service"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "paswd"
      POSTGRES_DB: "dbname"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./load-data:/load-data
    ports:
      - "5434:5432"
```

Please help me to resolve the issue.

### TimescaleDB version affected

2.10.2

### PostgreSQL version used

14.4

### What operating system did you use?

Ubuntu 20.04.3 LTS

### What installation method did you use?

Docker

### What platform did you run on?

Microsoft Azure Cloud

### How can we reproduce the bug?

```bash
No
```
