### ISSUE TITLE
[Bug]: Invalidation threshold for hypertable <n> not found

### ISSUE THREAD

**Issue by Xydez** [timescale/timescaledb#6389]
### What type of bug is this?

Other

### What subsystems and features are affected?

Backup, Continuous aggregate, Restore

### What happened?

I would like `refresh_continous_aggregate` to work after a pg_restore.

I have attempted to "initialize" the watermarks by running this, but to no avail

```sql
INSERT INTO "_timescaledb_catalog\".continuous_aggs_watermark (mat_hypertable_id, watermark) VALUES ($WATERMARK, 0);
```

### TimescaleDB version affected

2.12.2

### PostgreSQL version used

PostgreSQL 15.4 on x86_64-pc-linux-musl

### What operating system did you use?

Arch Linux x86_64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```
ERROR:  invalidation threshold for hypertable 1 not found
DETAIL:  Assertion 'found' failed.
```

### How can we reproduce the bug?

```yml
docker-compose.yml

version: "3"

services:
  postgres:
    container_name: postgres
    image: timescale/timescaledb:latest-pg15
    restart: always
    shm_size: 512mb
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_ROOT_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
      - ./tsdb.bak:/tsdb.bak
    command: postgres -c 'max_connections=250' -c 'fsync=off'

volumes:
  db:
```

1. Start the container
```bash
$ docker compose up -d
```

*replace the $VARIABLE*

2. Initialize the restore
```sql
DROP DATABASE IF EXISTS $DATABASE;
CREATE DATABASE $DATABASE;
CREATE EXTENSION IF NOT EXISTS timescaledb;
SELECT timescaledb_pre_restore();
```

3. Run pg_restore
```bash
$ docker exec "$CONTAINER" pg_restore \
    -d $DATABASE_DB_URL \
    -Fc tsdb.bak || exit 1
```

4. Finalize the restore
```sql
SELECT timescaledb_post_restore();
```

5. Refresh a continous aggregate
```sql
CALL refresh_continuous_aggregate('$AGGREGATE', '2015-01-01', now())
```

This results in the above stack trace.
