### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by skovzhaw** [timescale/timescaledb#91]
Hey guys,

I am trying to bring up TimescaleDB via Docker Compose (as opposed to Docker run) and it seems to me that the extension is not being loaded.

**Dockerfile**
```Dockerfile
FROM timescale/timescaledb

ENV PGDATA=/var/lib/postgresql/data/timescaledb
VOLUME /var/lib/postgresql
EXPOSE 5432

ADD initialize.sh /docker-entrypoint-initdb.d/init-user-db.sh
```

**initialize.sh**
```Bash
#!/bin/bash

psql --username "$POSTGRES_USER" <<EOF
CREATE DATABASE my_db WITH OWNER $POSTGRES_USER;
GRANT ALL PRIVILEGES ON DATABASE my_db TO $POSTGRES_USER;

\c my_db
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

CREATE TABLE IF NOT EXISTS  my_table (
  time      TIMESTAMP         NOT NULL,
  metric    TEXT              NOT NULL,
  usage     DOUBLE PRECISION  NOT NULL
);
SELECT create_hypertable('my_table', 'time');
CREATE INDEX IF NOT EXISTS usage_metric ON my_table (metric, time DESC);
EOF
```

Compose.yml
```Yaml
version: '3'

services:
  timescale:
    image: my_timescale
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    volumes:
      - ./timescale:/var/lib/postgresql
```

As you can see I am trying to load _timescaledb_ extension via `command: postgres -c shared_preload_libraries=timescaledb` but it looks like nothing is happening. This is what I get as an output:

```
NOTICE:  installing required extension "postgres_fdw"
ERROR:  The timescaledb library is not preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

  This can be done by editing the config file at: /var/lib/postgresql/data/timescaledb/postgresql.conf
  and adding 'timescaledb' to the list in the shared_preload_libraries config.

    # Modify postgresql.conf:
      shared_preload_libraries = 'timescaledb'

  Another way to do this, if not preloading other libraries, is with the command:
  echo "shared_preload_libraries = 'timescaledb'" >> /var/lib/postgresql/data/timescaledb/postgresql.conf 

  (Will require a database restart.)

  If you REALLY know what you are doing and would like to load the library without preloading, you can disable   this check with: 
    SET timescaledb.allow_install_without_preload = 'on';

STATEMENT:  CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
```

And consequently that's why _create_hypertable_ fails.

Starting TimescaleDB via Docker run works for me without any issues. I also tried to put aftermentioned `postgres -c shared_preload_libraries=timescaledb` command to Dockerfile, but it did not help.

Am I missing something? How are you doing your Docker compose?

Thanks in advance.

Best wishes,
Martin
